# Set to true to add reviewers to pull requests
addReviewers: true

# Set addAssignees to 'author' to set the PR creator as the assignee.
addAssignees: author

reviewers:
  - moriyoshi-kasuga

numberOfReviewers: 0

runOnDraft: true
