[tool.ruff]
line-length = 88

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = [
  "F",   # Pyflakes
  "E",   # pycodestyle (Error)
  "W",   # pycodestyle (Warning)
  "I",   # isort
  "N",   # pep8-naming
  "D",   # pydocstyle
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "SIM", # flake8-simplify
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
  "RUF", # Ruff-specific rules
]

ignore = [
  "B905", # `zip()` without `strict=`
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D203",
  "D212",
  "D415",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = ["tests"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "S101"]
